---

# Travis configuration

dist: 'trusty'
sudo: 'required'

services:
  - 'docker'

language: 'python'

env:
  matrix:
    - TOXENV='py27-ansible20'
    - TOXENV='py27-ansible21'
    - TOXENV='py27-ansible22'
    - TOXENV='py27-ansible23'

before_install:
  - 'sudo apt-get update -qq'
  - 'sudo apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y docker-engine'

script:
  - 'pip install tox-travis'

script:
  - 'tox -e "${TOXENV}"'

notifications:
  webhooks: 'https://galaxy.ansible.com/api/v1/notifications/'
