---

# Main tasks file for maxmind-geoip role

- name: 'INIT | Manage variables to use for our target'
  include: "{{ role_path }}/tasks/manage_variables.yml"
  tags:
    - 'role::maxmind-geoip'
    - 'role::maxmind-geoip::init'


- name: 'INSTALL | Manage OS family installation tasks'
  include: "{{ role_path }}/tasks/install/{{ ansible_os_family | lower }}_family.yml"
  become: True
  tags:
    - 'role::maxmind-geoip'
    - 'role::maxmind-geoip::install'


- name: 'UPDATE DATABASES | Databases update tasks without using geoipupdate'
  include: "{{ role_path }}/tasks/update/update_without_geoipupdate.yml"
  become: True
  when: 'maxmind_geoip_update_databases_without_geoipupdate'
  tags:
    - 'role::maxmind-geoip'
    - 'role::maxmind-geoip::update-databases'
