---

# Main tasks file for maxmind-geoip role

- name: 'INIT | Manage variables to use for our target'
  include_tasks: "{{ role_path }}/tasks/manage_variables.yml"
  tags:
    - 'role::maxmind-geoip'
    - 'role::maxmind-geoip::init'


- name: 'INSTALL | Manage OS family installation tasks'
  include_tasks: "{{ role_path }}/tasks/install/{{ ansible_os_family | lower }}_family.yml"
  become: True
  tags:
    - 'role::maxmind-geoip'
    - 'role::maxmind-geoip::install'


- name: 'UPDATE DATABASES | Databases update tasks using geoipupdate'
  include_tasks: "{{ role_path }}/tasks/update/update_with_geoipupdate.yml"
  become: True
  when:
    - maxmind_geoip_update_databases
    - maxmind_geoip_geoipupdate_managed
    - maxmind_geoip_update_databases_with_geoipupdate
  tags:
    - 'role::maxmind-geoip'
    - 'role::maxmind-geoip::update-databases'


- name: 'UPDATE DATABASES | Databases update tasks without using geoipupdate'
  include_tasks: "{{ role_path }}/tasks/update/update_without_geoipupdate.yml"
  become: True
  when:
    - maxmind_geoip_update_databases
    - not maxmind_geoip_update_databases_with_geoipupdate
  tags:
    - 'role::maxmind-geoip'
    - 'role::maxmind-geoip::update-databases'
