---

# Databases update tasks with geoipupdate
#------------------------------------------------------------------------------

- name: 'INSTALL | Ensure database folder path exists'
  file:
    dest: "{{ maxmind_geoip_databases.dest_folder_path }}"
    state: 'directory'
    owner: "{{ maxmind_geoip_files_owner }}"
    group: "{{ maxmind_geoip_files_group }}"
    mode: "{{ maxmind_geoip_files_mode }}"


- name: 'INSTALL | Run databases update'
  command: '/usr/local/bin/geoipupdate'
