---

dependency:
  name: 'galaxy'
driver:
  name: 'docker'
lint:
  name: 'yamllint'
platforms:
  - name: "maxmind-geoip-docker-jessie"
    image: 'minimum2scp/systemd-jessie:latest'
    command: '/sbin/init'
    cap_add:
      - 'SYS_PTRACE'
    privileged: True
  - name: "maxmind-geoip-docker-xenial"
    image: 'solita/ubuntu-systemd:16.04'
    command: '/sbin/init'
    cap_add:
      - 'SYS_PTRACE'
    privileged: True
  - name: "maxmind-geoip-docker-trusty"
    image: 'ubuntu:trusty'
    cap_add:
      - 'SYS_PTRACE'
    privileged: True
  - name: "maxmind-geoip-docker-bionic"
    image: 'solita/ubuntu-systemd:18.04'
    command: '/sbin/init'
    cap_add:
      - 'SYS_PTRACE'
    privileged: True
provisioner:
  name: 'ansible'
  lint:
    name: 'ansible-lint'
  inventory:
    group_vars:
      all:
        maxmind_geoip_update_databases: True
    host_vars:
      maxmind-geoip-docker-jessie:
        maxmind_geoip_update_databases_with_geoipupdate: False
      maxmind-geoip-docker-trusty:
        maxmind_geoip_geoipupdate_changed_when: False
        maxmind_geoip_update_databases_with_geoipupdate: True
      maxmind-geoip-docker-xenial:
        maxmind_geoip_geoipupdate_changed_when: False
        maxmind_geoip_update_databases_with_geoipupdate: True
      maxmind-geoip-docker-bionic:
        maxmind_geoip_geoipupdate_changed_when: False
        maxmind_geoip_update_databases_with_geoipupdate: True
scenario:
  name: 'default'
verifier:
  name: 'testinfra'
  additional_files_or_dirs:
    - '../../tests'
  lint:
    name: 'flake8'
  options:
    sudo: True
